name: animated_notch_bottom_bar_no_border_radius
description: This package helps you to achieve animated notch bottom navigation bar with any widget as children.
version: 1.0.0
repository : https://github.com/AbinayanRatna/animated_notch_bottom_bar_no_border_radius
issue_tracker: https://github.com/AbinayanRatna/animated_notch_bottom_bar_no_border_radius/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

